#!/bin/bash
#
# Seed the getting-started working files for a given part of the walk-through guide.
#
# The repository tracks only *variants* of the files SDLB actually reads
# (config/*.conf.part-*-solution, config/config.template, envConfig/dev.conf.part-2-solution,
# src/main/scala/com/sample/CustomWebserviceDataObject.scala.part-*). This script activates the
# right ones, i.e. it puts the working tree into the state a reader should *start* a part from.
#
# Note "prepare <part>" seeds the STARTING point of that part, which is the previous part's
# solution - preparing part 3 lays down the part-2 solution, not the part-3 one. Use "final"
# for the completed pipeline.
#
# The part-Xa / part-Xb variants are intermediate results of the sub-chapters within a part and
# are not seeding targets; they are there to compare against while working through a part.
#
# Guide source: https://github.com/smart-data-lake/smart-data-lake/tree/develop-spark4/docs/docs/getting-started
#
set -euo pipefail

cd "$(dirname "$0")"

CONFIGS=(airports departures btl)
SCALA_DIR="src/main/scala/com/sample"
SCALA_ACTIVE="$SCALA_DIR/CustomWebserviceDataObject.scala"

# Generated by a local run (basePath is "./"), safe to delete between parts.
GENERATED=(stg-airports stg-departures int-airports int-departures \
           btl-connected-airports btl-departures-arrivals-airports btl-distances \
           spark-warehouse metastore_db derby.log)

# Java 17 needs these for Spark.
JAVA_OPTIONS="--add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED"

DRY_RUN=false
CLEAN=false
VALIDATE=false
PART=""

usage() {
  cat <<'USAGE'
Usage: ./prepare.sh <part> [options]
       ./prepare.sh --list

Parts:
  1        empty configs (config.template)              - start of part 1
  2        part-1 solution                              - start of part 2
  3        part-2 solution + dev.conf + the initial
           CustomWebserviceDataObject                   - start of part 3
  final    complete part-3 solution                     - finished pipeline

Options:
  --clean      also delete output generated by previous local runs, and
               viz/state/current (in-progress run state). Tracked files are never touched.
  --validate   after seeding, validate the configuration with SDLB "--test config"
               (requires a built project: mvn clean package)
  --dry-run    print what would happen, change nothing
  --list       print the part -> file mapping and exit
  -h, --help   this text
USAGE
}

mapping() {
  cat <<'MAP'
part   config/airports.conf         config/departures.conf         config/btl.conf                envConfig/dev.conf          CustomWebserviceDataObject.scala
----   --------------------------   ----------------------------   ----------------------------   -------------------------   --------------------------------
1      config.template             config.template                config.template               (unchanged)                 (removed)
2      airports.conf.part-1-sol.   departures.conf.part-1-sol.    btl.conf.part-1-sol.          (unchanged)                 (removed)
3      airports.conf.part-2-sol.   departures.conf.part-2-sol.    btl.conf.part-2-sol.          dev.conf.part-2-solution    .part-3a-initial
final  airports.conf.part-3-sol.   departures.conf.part-3-sol.    btl.conf.part-3-sol.          dev.conf.part-2-solution    .part-3-solution
MAP
}

while [ $# -gt 0 ]; do
  case "$1" in
    --clean)    CLEAN=true ;;
    --validate) VALIDATE=true ;;
    --dry-run)  DRY_RUN=true ;;
    --list)     mapping; exit 0 ;;
    -h|--help)  usage; exit 0 ;;
    -*)         echo "prepare.sh: unknown option '$1'" >&2; usage >&2; exit 2 ;;
    *)          if [ -n "$PART" ]; then echo "prepare.sh: only one part may be given" >&2; exit 2; fi
                PART="$1" ;;
  esac
  shift
done

if [ -z "$PART" ]; then usage >&2; exit 2; fi

# Resolve the part to a source suffix for the config files, plus the extra files it needs.
case "$PART" in
  1)     CONFIG_SRC="template"; DEV_CONF=false; SCALA_SRC="" ;;
  2)     CONFIG_SRC="part-1-solution"; DEV_CONF=false; SCALA_SRC="" ;;
  3)     CONFIG_SRC="part-2-solution"; DEV_CONF=true;  SCALA_SRC="part-3a-initial" ;;
  final) CONFIG_SRC="part-3-solution"; DEV_CONF=true;  SCALA_SRC="part-3-solution" ;;
  *)     echo "prepare.sh: unknown part '$PART' (expected 1, 2, 3 or final)" >&2; exit 2 ;;
esac

run() {
  if $DRY_RUN; then echo "  [dry-run] $*"; else "$@"; fi
}

copy() {
  local src="$1" dst="$2"
  if [ ! -f "$src" ]; then echo "prepare.sh: missing source file '$src'" >&2; exit 1; fi
  echo "  $dst  <-  $src"
  run cp "$src" "$dst"
}

# Delete a generated path, but never something git tracks.
remove_generated() {
  local path="$1"
  [ -e "$path" ] || return 0
  if [ -n "$(git ls-files -- "$path" 2>/dev/null)" ]; then
    echo "  skipping $path (tracked by git)"
    return 0
  fi
  echo "  removing $path"
  run rm -rf "$path"
}

echo "Preparing getting-started for part '$PART'"
$DRY_RUN && echo "(dry run - nothing will be changed)"

for c in "${CONFIGS[@]}"; do
  if [ "$CONFIG_SRC" = "template" ]; then
    copy "config/config.template" "config/$c.conf"
  else
    copy "config/$c.conf.$CONFIG_SRC" "config/$c.conf"
  fi
done

if $DEV_CONF; then
  copy "envConfig/dev.conf.part-2-solution" "envConfig/dev.conf"
fi

if [ -n "$SCALA_SRC" ]; then
  copy "$SCALA_ACTIVE.$SCALA_SRC" "$SCALA_ACTIVE"
elif [ -f "$SCALA_ACTIVE" ]; then
  # Not part of parts 1 and 2 - it is introduced in part 3.
  echo "  removing $SCALA_ACTIVE (not used before part 3)"
  run rm -f "$SCALA_ACTIVE"
fi

if $CLEAN; then
  echo "Cleaning output of previous runs"
  for g in "${GENERATED[@]}"; do remove_generated "$g"; done
  remove_generated "viz/state/current"
fi

if $VALIDATE && [ "$PART" = "1" ]; then
  echo "Skipping validation: part 1 starts from empty configs, so no action can be selected yet."
elif $VALIDATE; then
  echo "Validating configuration with SDLB --test config"
  if $DRY_RUN; then
    echo "  [dry-run] mvn exec:exec ... --test config"
  elif [ ! -d target/classes ]; then
    echo "  cannot validate: target/classes is missing - run 'mvn clean package' first" >&2
    exit 1
  else
    CFG="./config"
    if grep -qs '\${env\.' config/*.conf; then CFG="./config,./envConfig/dev.conf"; fi
    echo "  --config $CFG"
    JAVA_OPTIONS="$JAVA_OPTIONS" mvn -B -ntp exec:exec \
      -Dexec.executable="java" \
      -Dexec.args="$JAVA_OPTIONS -cp %classpath io.smartdatalake.app.DefaultSmartDataLakeBuilder --test config --feed-sel .* --config $CFG -n prepare-check"
  fi
fi

echo "Done."
