#!/bin/bash
#
# Seed the getting-started working files for a given part of the walk-through guide.
#
# The repository tracks only *variants* of the files SDLB actually reads
# (config/*.conf.part-*-solution, config/config.template, envConfig/dev.conf.part-2-solution,
# src/main/scala/com/sample/CustomWebserviceDataObject.scala.part-*). This script activates the
# right ones, i.e. it puts the working tree into the state a reader should *start* a part from.
#
# Note "prepare <part>" seeds the STARTING point of that part, which is the previous part's
# solution - preparing part 3 lays down the part-2 solution, not the part-3 one. Use "final"
# for the completed pipeline.
#
# The part-Xa / part-Xb variants are intermediate results of the sub-chapters within a part and
# are not seeding targets; they are there to compare against while working through a part.
#
# Guide source: https://github.com/smart-data-lake/smart-data-lake/tree/develop-spark4/docs/docs/getting-started
#
set -euo pipefail

cd "$(dirname "$0")"

CONFIGS=(airports departures btl)
SCALA_DIR="src/main/scala/com/sample"
SCALA_ACTIVE="$SCALA_DIR/CustomWebserviceDataObject.scala"

# Generated by a run, safe to delete between parts. A local run resolves the relative paths in
# the configs against the process working directory, so these land in the repository root; a
# container run through startJob.sh gets -Duser.dir=/mnt/data, so they land in data/ instead.
# Both are cleaned.
GENERATED=(stg-airports stg-departures int-airports int-departures \
           btl-connected-airports btl-departures-arrivals-airports btl-distances \
           spark-warehouse metastore_db derby.log)
GENERATED_PREFIXES=("" "data/")

# The OpenSky API refuses anonymous requests that reach too far back or span too long an
# interval (403 "You cannot access historical flights"): a 12h interval is served, 18h is not,
# and an old interval is refused however narrow it is. The part-1/2 configs carry a hardcoded
# 2021 window, so it is rewritten to "the last WINDOW_SECONDS" when those configs are seeded.
# Part 3 onwards needs no rewrite - CustomWebserviceDataObject computes its window in Scala.
WINDOW_SECONDS=$((6 * 3600))
DEPARTURES_CONF="config/departures.conf"

# Java 17 needs these for Spark.
JAVA_OPTIONS="--add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED"

DRY_RUN=false
CLEAN=false
VALIDATE=false
KEEP_TIMESTAMPS=false
FIX_ONLY=false
PART=""

usage() {
  cat <<'USAGE'
Usage: ./prepare.sh <part> [options]
       ./prepare.sh --list

Parts:
  1        empty configs (config.template)              - start of part 1
  2        part-1 solution                              - start of part 2
  3        part-2 solution + dev.conf + the initial
           CustomWebserviceDataObject                   - start of part 3
  final    complete part-3 solution                     - finished pipeline

Options:
  --clean      also delete output generated by previous local runs, and
               viz/state/current (in-progress run state). Tracked files are never touched.
  --keep-timestamps
               leave the hardcoded 2021 OpenSky window in config/departures.conf as the
               guide prints it. Without this the window is rewritten to the last 6h, because
               the API refuses the original one for anonymous callers (403).
  --fix-timestamps
               only rewrite that window in the current config/departures.conf and exit; no
               part needs to be given. Useful after copying a part-2a/2b variant by hand.
  --validate   after seeding, validate the configuration with SDLB "--test config"
               (requires a built project: mvn clean package)
  --dry-run    print what would happen, change nothing
  --list       print the part -> file mapping and exit
  -h, --help   this text
USAGE
}

mapping() {
  cat <<'MAP'
part   config/airports.conf         config/departures.conf         config/btl.conf                envConfig/dev.conf          CustomWebserviceDataObject.scala
----   --------------------------   ----------------------------   ----------------------------   -------------------------   --------------------------------
1      config.template             config.template                config.template               (unchanged)                 (removed)
2      airports.conf.part-1-sol.   departures.conf.part-1-sol.    btl.conf.part-1-sol.          (unchanged)                 (removed)
3      airports.conf.part-2-sol.   departures.conf.part-2-sol.    btl.conf.part-2-sol.          dev.conf.part-2-solution    .part-3a-initial
final  airports.conf.part-3-sol.   departures.conf.part-3-sol.    btl.conf.part-3-sol.          dev.conf.part-2-solution    .part-3-solution

Parts 2 and 3 seed a departures.conf whose OpenSky URL carries a hardcoded 2021 time window.
That window is rewritten to the last 6h so the API accepts it without an account; pass
--keep-timestamps to leave it exactly as the guide prints it. Part 1 has no URL yet, and
"final" needs no rewrite because CustomWebserviceDataObject computes its window in Scala.
MAP
}

run() {
  if $DRY_RUN; then echo "  [dry-run] $*"; else "$@"; fi
}

copy() {
  local src="$1" dst="$2"
  if [ ! -f "$src" ]; then echo "prepare.sh: missing source file '$src'" >&2; exit 1; fi
  echo "  $dst  <-  $src"
  run cp "$src" "$dst"
}

# Rewrite a hardcoded "begin=<epoch>&end=<epoch>" webservice window to the last
# WINDOW_SECONDS, so that anonymous OpenSky requests are accepted. Only the activated copy is
# touched - never the tracked .part-* variants.
fix_timestamps() {
  local f="$DEPARTURES_CONF"
  if [ ! -f "$f" ]; then
    echo "  no $f to adjust"
    return 0
  fi
  if ! grep -qE 'begin=[0-9]+&end=[0-9]+' "$f"; then
    echo "  no hardcoded time window in $f (nothing to adjust)"
    return 0
  fi
  local end begin
  end=$(date +%s)
  begin=$((end - WINDOW_SECONDS))
  echo "  $f: time window -> begin=$begin end=$end (the last $((WINDOW_SECONDS / 3600))h)"
  if $DRY_RUN; then
    echo "  [dry-run] sed -E 's|begin=[0-9]+&end=[0-9]+|begin=$begin&end=$end|g' $f"
    return 0
  fi
  local tmp
  tmp=$(mktemp)
  # No sed -i: its in-place flag differs between GNU and BSD. "\&" keeps sed from expanding
  # "&" to the whole match.
  sed -E "s|begin=[0-9]+&end=[0-9]+|begin=${begin}\&end=${end}|g" "$f" > "$tmp"
  mv "$tmp" "$f"
}

# Delete a generated path, but never something git tracks.
remove_generated() {
  local path="$1"
  [ -e "$path" ] || return 0
  if [ -n "$(git ls-files -- "$path" 2>/dev/null)" ]; then
    echo "  skipping $path (tracked by git)"
    return 0
  fi
  echo "  removing $path"
  run rm -rf "$path"
}

while [ $# -gt 0 ]; do
  case "$1" in
    --clean)    CLEAN=true ;;
    --validate) VALIDATE=true ;;
    --dry-run)  DRY_RUN=true ;;
    --keep-timestamps) KEEP_TIMESTAMPS=true ;;
    --fix-timestamps)  FIX_ONLY=true ;;
    --list)     mapping; exit 0 ;;
    -h|--help)  usage; exit 0 ;;
    -*)         echo "prepare.sh: unknown option '$1'" >&2; usage >&2; exit 2 ;;
    *)          if [ -n "$PART" ]; then echo "prepare.sh: only one part may be given" >&2; exit 2; fi
                PART="$1" ;;
  esac
  shift
done

if $FIX_ONLY; then
  if [ -n "$PART" ]; then
    echo "prepare.sh: --fix-timestamps adjusts the current config and takes no part" >&2
    exit 2
  fi
  echo "Adjusting the OpenSky time window"
  fix_timestamps
  echo "Done."
  exit 0
fi

if [ -z "$PART" ]; then usage >&2; exit 2; fi

# Resolve the part to a source suffix for the config files, plus the extra files it needs.
case "$PART" in
  1)     CONFIG_SRC="template"; DEV_CONF=false; SCALA_SRC="" ;;
  2)     CONFIG_SRC="part-1-solution"; DEV_CONF=false; SCALA_SRC="" ;;
  3)     CONFIG_SRC="part-2-solution"; DEV_CONF=true;  SCALA_SRC="part-3a-initial" ;;
  final) CONFIG_SRC="part-3-solution"; DEV_CONF=true;  SCALA_SRC="part-3-solution" ;;
  *)     echo "prepare.sh: unknown part '$PART' (expected 1, 2, 3 or final)" >&2; exit 2 ;;
esac


echo "Preparing getting-started for part '$PART'"
$DRY_RUN && echo "(dry run - nothing will be changed)"

for c in "${CONFIGS[@]}"; do
  if [ "$CONFIG_SRC" = "template" ]; then
    copy "config/config.template" "config/$c.conf"
  else
    copy "config/$c.conf.$CONFIG_SRC" "config/$c.conf"
  fi
done

if $DEV_CONF; then
  copy "envConfig/dev.conf.part-2-solution" "envConfig/dev.conf"
fi

if [ -n "$SCALA_SRC" ]; then
  copy "$SCALA_ACTIVE.$SCALA_SRC" "$SCALA_ACTIVE"
elif [ -f "$SCALA_ACTIVE" ]; then
  # Not part of parts 1 and 2 - it is introduced in part 3.
  echo "  removing $SCALA_ACTIVE (not used before part 3)"
  run rm -f "$SCALA_ACTIVE"
fi

if $KEEP_TIMESTAMPS; then
  echo "  keeping the config's own OpenSky time window (--keep-timestamps)"
else
  fix_timestamps
fi

if $CLEAN; then
  echo "Cleaning output of previous runs"
  for prefix in "${GENERATED_PREFIXES[@]}"; do
    for g in "${GENERATED[@]}"; do remove_generated "$prefix$g"; done
  done
  remove_generated "viz/state/current"
fi

if $VALIDATE && [ "$PART" = "1" ]; then
  echo "Skipping validation: part 1 starts from empty configs, so no action can be selected yet."
elif $VALIDATE; then
  echo "Validating configuration with SDLB --test config"
  if $DRY_RUN; then
    echo "  [dry-run] mvn exec:exec ... --test config"
  elif [ ! -d target/classes ]; then
    echo "  cannot validate: target/classes is missing - run 'mvn clean package' first" >&2
    exit 1
  else
    CFG="./config"
    if grep -qs '\${env\.' config/*.conf; then CFG="./config,./envConfig/dev.conf"; fi
    echo "  --config $CFG"
    JAVA_OPTIONS="$JAVA_OPTIONS" mvn -B -ntp exec:exec \
      -Dexec.executable="java" \
      -Dexec.args="$JAVA_OPTIONS -cp %classpath io.smartdatalake.app.DefaultSmartDataLakeBuilder --test config --feed-sel .* --config $CFG -n prepare-check"
  fi
fi

echo "Done."
