name: Build, Run Getting Started, and Deploy UI

on:
  push:
    branches:
      - feature/729-add-ui-demo-v1

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with: 
        distribution: 'temurin'
        java-version: '11'  # You can specify the Java version you need for your project
      
    - name: Build with Maven Package
      run: mvn clean package
      
    - name: Run Getting Started
      run: mvn exec:exec -Dexec.executable="java" -Dexec.args="-cp %classpath io.smartdatalake.app.LocalSmartDataLakeBuilder --feed-sel .* --config config/application.conf --state-path data/state -n getting-started"
      
    - name: Commit and Push New State File
      run: |
        git add data/state/
        git commit -m "Update state file"
        git push
    
    
  deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download and Unzip Latest UI Snapshot
          run: wget https://nightly.link/smart-data-lake/sdl-visualization/workflows/build/develop/sdl-visualizer.zip && unzip sdl-visualizer.zip -d ./viz
            
        - name: Create Config and State Files
          run: |
              mkdir viz/config
              mkdir viz/state

        - name: list path
          run: |
              pwd
        
        - name: list path
          run: |
            ls 

        - name: Copy Config and State Files
          run: |
             cp config/application.conf viz/config
             cp data/state/succeeded/*.json viz/state
                
          
         