name: Build, Run Getting Started, and Deploy UI

on:
  push:
    branches:
      - feature/729-add-ui-demo-v1

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with: 
        distribution: 'temurin'
        java-version: '11'  # You can specify the Java version you need for your project
      
    - name: Build with Maven Package
      run: mvn clean package
      
    - name: Run Getting Started
      run: mvn exec:exec -Dexec.executable="java" -Dexec.args="-cp %classpath io.smartdatalake.app.LocalSmartDataLakeBuilder --feed-sel .* --config config/application.conf --state-path viz/state -n getting-started"
      
    - name: Commit and Push New State File
      run: |
        git config --global user.email "jss629@hotmail.com"
        git config --global user.name "dust629"
        git add viz/state/
        git commit -m "Update state file"
        git push

    # - name: Copy Config File
    #   run: |
    #      mkdir viz/config
    #      cp config/application.conf viz/config

    # - name: Download and Unzip Latest UI Snapshot
    #   run: wget https://nightly.link/smart-data-lake/sdl-visualization/workflows/build/develop/sdl-visualizer.zip && unzip sdl-visualizer.zip -d -n ./viz
        
    
    # - name: Run build_index.sh script
    #   run: |
    #       chmod +x ./build_index.sh  
    #       ./build_index.sh /state /config
    #   working-directory: viz/
   
    # - name: list path
    #   run: |
    #     ls 


            
          
         